# Generated by Django 5.1.15 on 2026-09-20 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("cash_start", models.BigIntegerField(default=0)),
                (
                    "cash_end",
                    models.BigIntegerField(
                        blank=True, help_text="hisoblangan haqiqiy naqd", null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_shifts",
                        to="core.branch",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField(db_index=True, editable=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("dine_in", "Zalda"),
                            ("takeaway", "Olib ketish"),
                            ("delivery", "Yetkazib berish"),
                        ],
                        default="takeaway",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ochiq"),
                            ("paid", "To'langan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("table_no", models.CharField(blank=True, max_length=12)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("customer_name", models.CharField(blank=True, max_length=80)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("subtotal", models.BigIntegerField(default=0)),
                ("discount", models.BigIntegerField(default=0)),
                ("total", models.BigIntegerField(default=0)),
                (
                    "cost_total",
                    models.BigIntegerField(
                        default=0, help_text="tannarx yig'indisi (snapshot)"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Naqd"),
                            ("card", "Karta (terminal)"),
                            ("click", "Click"),
                            ("payme", "Payme"),
                            ("uzum", "Uzum"),
                            ("transfer", "O'tkazma"),
                        ],
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        default="pos",
                        help_text="pos | site | telegram | app",
                        max_length=12,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.branch",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="pos.cashshift",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("qty", models.PositiveIntegerField(default=1)),
                ("price", models.BigIntegerField(help_text="sotuv narxi (snapshot)")),
                (
                    "cost",
                    models.BigIntegerField(default=0, help_text="tannarx (snapshot)"),
                ),
                (
                    "modifiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"name": "...", "price": 0}]',
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=120)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pos.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
