# Generated by Django 5.1.15 on 2026-09-29 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashshift",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="card_terminal",
            field=models.BigIntegerField(
                blank=True,
                help_text="terminal Z-hisoboti bo'yicha karta summasi",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="counted",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='kupyuralar: {"200000": 3, "100000": 5, ...}',
            ),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="diff_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="handed_amount",
            field=models.BigIntegerField(
                blank=True, help_text="topshirilgan naqd", null=True
            ),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="handed_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="left_amount",
            field=models.BigIntegerField(
                blank=True,
                help_text="kassada keyingi smenaga qoldirilgan naqd",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CashMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("in", "Kirim"), ("out", "Chiqim")], max_length=3
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("reason", models.CharField(max_length=160)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="pos.cashshift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
