# Generated by Django 5.1.15 on 2026-09-20 18:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='stol raqami yoki nomi: 12, A3, VIP-1', max_length=12)),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('shape', models.CharField(choices=[('square', "To'rtburchak"), ('round', 'Dumaloq'), ('long', 'Uzun')], default='square', max_length=8)),
                ('x', models.FloatField(default=10, help_text='zal xaritasidagi joyi, % (0-100)')),
                ('y', models.FloatField(default=10)),
                ('size', models.PositiveSmallIntegerField(default=1, help_text="1 kichik, 2 o'rta, 3 katta")),
                ('needs_cleaning', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.branch')),
            ],
            options={
                'ordering': ['zone__sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guests', models.PositiveSmallIntegerField(default=2)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bill_asked_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.BigIntegerField(default=0, help_text='yopilgandagi chek summasi (snapshot)')),
                ('source', models.CharField(default='hall', help_text='hall | pos | reservation', max_length=12)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_sessions', to='pos.order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tables.table')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#0F6E63', max_length=9)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.branch')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='tables.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('branch', 'number')},
        ),
    ]
