# Generated by Django 5.1.15 on 2026-09-19 18:48

import django.utils.timezone
import simple_history.models
from django.db import migrations, models

import modules.catalog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BranchPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.JSONField(default=modules.catalog.models.empty_i18n)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="catalog/categories/"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("custom_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCategory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.JSONField(default=modules.catalog.models.empty_i18n)),
                ("image", models.TextField(blank=True, max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("custom_data", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical category",
                "verbose_name_plural": "historical categorys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.JSONField(default=modules.catalog.models.empty_i18n)),
                (
                    "description",
                    models.JSONField(
                        blank=True, default=modules.catalog.models.empty_i18n
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=40)),
                (
                    "price",
                    models.BigIntegerField(
                        default=0, help_text="asosiy sotuv narxi, so'm"
                    ),
                ),
                (
                    "cost",
                    models.BigIntegerField(
                        default=0,
                        help_text="tannarx, so'm (ombor moduli avtomatik yangilaydi)",
                    ),
                ),
                ("image", models.TextField(blank=True, max_length=100)),
                ("weight_g", models.PositiveIntegerField(blank=True, null=True)),
                ("kcal", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text='["hit", "new", "spicy"]'
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "in_stop_list",
                    models.BooleanField(
                        default=False,
                        help_text="vaqtincha yo'q (kassa/saytda ko'rinmaydi)",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "ikpu_code",
                    models.CharField(
                        blank=True,
                        help_text="fiskal chek uchun IKPU (4-bosqich)",
                        max_length=17,
                    ),
                ),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="egasi qo'shgan maydonlar"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical product",
                "verbose_name_plural": "historical products",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProduct_modifier_groups",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "HistoricalProduct_modifier_groups",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MenuVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_by", models.CharField(blank=True, max_length=120)),
                ("snapshot", models.JSONField()),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-version"],
                "get_latest_by": "version",
            },
        ),
        migrations.CreateModel(
            name="Modifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.JSONField(default=modules.catalog.models.empty_i18n)),
                (
                    "price",
                    models.BigIntegerField(
                        default=0, help_text="qo'shimcha narx, so'm"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ModifierGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.JSONField(default=modules.catalog.models.empty_i18n)),
                ("min_select", models.PositiveSmallIntegerField(default=0)),
                ("max_select", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.JSONField(default=modules.catalog.models.empty_i18n)),
                (
                    "description",
                    models.JSONField(
                        blank=True, default=modules.catalog.models.empty_i18n
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=40)),
                (
                    "price",
                    models.BigIntegerField(
                        default=0, help_text="asosiy sotuv narxi, so'm"
                    ),
                ),
                (
                    "cost",
                    models.BigIntegerField(
                        default=0,
                        help_text="tannarx, so'm (ombor moduli avtomatik yangilaydi)",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="catalog/products/")),
                ("weight_g", models.PositiveIntegerField(blank=True, null=True)),
                ("kcal", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text='["hit", "new", "spicy"]'
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "in_stop_list",
                    models.BooleanField(
                        default=False,
                        help_text="vaqtincha yo'q (kassa/saytda ko'rinmaydi)",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "ikpu_code",
                    models.CharField(
                        blank=True,
                        help_text="fiskal chek uchun IKPU (4-bosqich)",
                        max_length=17,
                    ),
                ),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="egasi qo'shgan maydonlar"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
