# Generated by Django 5.1.15 on 2026-09-19 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="branchprice",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="historicalcategory",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct_modifier_groups",
            name="history",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="catalog.historicalproduct",
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="catalog.modifiergroup",
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct_modifier_groups",
            name="modifiergroup",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="catalog.modifiergroup",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="modifier_groups",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.modifiergroup"
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct_modifier_groups",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_tablespace="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="branchprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_prices",
                to="catalog.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branchprice",
            unique_together={("product", "branch")},
        ),
    ]
