# Generated by Django 5.1.15 on 2026-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="internetdagi rasm havolasi (yuklash shart emas — baza tejaladi)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="internetdagi rasm havolasi (yuklash shart emas — baza tejaladi)",
                max_length=500,
            ),
        ),
    ]
