# Generated by Django 5.1.15 on 2026-09-25 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(blank=True, help_text="m | f", max_length=1),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        default="pos",
                        help_text="pos | telegram | site | manual | import",
                        max_length=12,
                    ),
                ),
                ("balance", models.BigIntegerField(default=0)),
                ("spent_total", models.BigIntegerField(default=0)),
                ("orders_count", models.PositiveIntegerField(default=0)),
                ("first_order_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_order_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "marketing_ok",
                    models.BooleanField(
                        default=True, help_text="aksiya xabarlarini olishga rozi"
                    ),
                ),
            ],
            options={
                "ordering": ["-last_order_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("percent", "Foiz chegirma"),
                            ("fixed", "Summa chegirma"),
                        ],
                        default="percent",
                        max_length=8,
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(help_text="foiz (1–100) yoki so'm"),
                ),
                (
                    "max_discount",
                    models.PositiveIntegerField(
                        default=0, help_text="foizda eng ko'p chegirma, 0 — cheksiz"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="bo'sh — avtomatik qo'llanadi",
                        max_length=30,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Hamma"),
                            ("new", "Yangi mijozlar (birinchi xarid)"),
                            ("birthday", "Tug'ilgan kuni yaqin"),
                            ("silver", "Kumush va Oltin"),
                            ("gold", "Faqat Oltin"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("min_order", models.PositiveIntegerField(default=0)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[0..6], 0 — dushanba; bo'sh — har kuni",
                    ),
                ),
                ("hour_from", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("hour_to", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "category_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="bo'sh — butun menyu"
                    ),
                ),
                ("product_ids", models.JSONField(blank=True, default=list)),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=0, help_text="0 — cheksiz"),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                (
                    "discount_total",
                    models.BigIntegerField(
                        default=0,
                        help_text="shu aksiya bo'yicha berilgan jami chegirma",
                    ),
                ),
                (
                    "revenue_total",
                    models.BigIntegerField(
                        default=0, help_text="aksiya qo'llangan cheklar summasi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BonusTxn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("earn", "Xariddan keshbek"),
                            ("spend", "Xaridda ishlatildi"),
                            ("welcome", "Xush kelibsiz sovg'asi"),
                            ("birthday", "Tug'ilgan kun sovg'asi"),
                            ("adjust", "Qo'lda o'zgartirildi"),
                            ("refund", "Qaytarildi (chek bekor)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.BigIntegerField(help_text="+ qo'shildi, − ayirildi")),
                ("order_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="txns",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField(unique=True)),
                ("promo_discount", models.BigIntegerField(default=0)),
                ("bonus_used", models.BigIntegerField(default=0)),
                ("earned", models.BigIntegerField(default=0)),
                (
                    "settled",
                    models.BooleanField(
                        default=False,
                        help_text="to'lov hisoblangan (bonus yechilgan / qo'shilgan)",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="crm.customer",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.promo",
                    ),
                ),
            ],
        ),
    ]
