# Generated by Django 5.1.15 on 2026-09-27 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0002_recruit_profile_kpi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("icon", models.CharField(default="🏢", max_length=8)),
                ("color", models.CharField(default="#2F80ED", max_length=9)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PositionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Rahbariyat"),
                            (2, "Direktor / bo'lim boshlig'i"),
                            (3, "Filial rahbari"),
                            (4, "Smena rahbari"),
                            (5, "Xodim"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("hq", "Bosh ofis"), ("branch", "Har bir filialda")],
                        default="branch",
                        max_length=6,
                    ),
                ),
                ("icon", models.CharField(default="👤", max_length=8)),
                (
                    "purpose",
                    models.TextField(
                        blank=True, help_text="lavozim nima uchun bor — bir-ikki gap"
                    ),
                ),
                (
                    "responsibilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"text": "...", "freq": "daily"}]',
                    ),
                ),
                (
                    "role_code",
                    models.CharField(
                        blank=True,
                        help_text="ishga olishda beriladigan tizim roli",
                        max_length=40,
                    ),
                ),
                (
                    "headcount",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="rejadagi shtat (filial lavozimi — har filialda)",
                    ),
                ),
                (
                    "template_key",
                    models.CharField(
                        blank=True,
                        help_text="shablondan yaratilgan bo'lsa — kalit",
                        max_length=30,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="ops.department",
                    ),
                ),
                (
                    "position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="hr.position",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.position",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "position__sort_order"],
            },
        ),
    ]
