# Generated by Django 5.1.15 on 2026-09-24 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("full_name", models.CharField(blank=True, max_length=160)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("language", models.CharField(default="uz", max_length=5)),
                (
                    "state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="suhbat qadami: {'step': 'book_guests', ...}",
                    ),
                ),
                ("orders_count", models.PositiveIntegerField(default=0)),
                ("spent_total", models.BigIntegerField(default=0)),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False, help_text="botni bloklagan — xabar yuborilmaydi"
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Hamma obunachilar"),
                            ("with_phone", "Telefon ulaganlar"),
                            ("buyers", "Xarid qilganlar"),
                        ],
                        default="all",
                        max_length=12,
                    ),
                ),
                ("button_text", models.CharField(blank=True, max_length=40)),
                ("button_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Qoralama"), ("sent", "Yuborildi")],
                        default="draft",
                        max_length=6,
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("sent", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
