"""
Tayyor tuzilma shabloni — oddiy restoran/fast-food uchun. Egasi bir bosishda yaratadi, keyin o'zgartiradi.
Mavjud lavozimlar nomi mos kelsa (masalan «Menejer» → Filial menejeri) — yangisi yaratilmaydi, o'shanga profil yoziladi.
"""

DEPARTMENTS = [
    ("mgmt", "Boshqaruv", "👑", "#374151", "Kompaniya va filiallarni boshqarish"),
    ("kitchen", "Oshxona", "👨‍🍳", "#E4572E", "Taom sifati, retsept va gigiyena"),
    ("hall", "Zal va servis", "🍽️", "#2F80ED", "Mehmonni kutib olish va xizmat"),
    ("cash", "Kassa", "💳", "#F2994A", "To'lov, chek va naqd pul nazorati"),
    ("hr", "HR (Kadrlar)", "🧑‍💼", "#27AE60", "Ishga olish, o'qitish, davomat"),
    ("marketing", "Marketing", "📣", "#9B51E0", "Reklama, aksiya va mijozlar bilan aloqa"),
    ("finance", "Moliya", "💰", "#C9A227", "Hisob-kitob, xarajat va foyda"),
    ("supply", "Ta'minot va ombor", "🚚", "#219653", "Xarid, ombor va yetkazib beruvchilar"),
    ("service", "Tozalik va texnik", "🧹", "#56A3C9", "Tozalik, jihozlar va ta'mirlash"),
]

D, W, M, S, N = "daily", "weekly", "monthly", "shift", "needed"

# (kalit, nomi, bo'lim, daraja, doira, kimga bo'ysunadi, rol, ikonka, shtat, [nom sinonimlari], maqsad, [(vazifa, takror)])
POSITIONS = [
    ("owner", "Rahbar (CEO)", "mgmt", 1, "hq", None, "owner", "👑", 1, ["CEO", "Direktor", "Egasi"],
     "Kompaniyaning umumiy strategiyasi, rivojlanishi va foydasi uchun javobgar.",
     [("Kompaniya strategiyasi va yillik rejani tasdiqlash", M), ("Filiallar natijasini (savdo, food cost, KPI) ko'rib chiqish", W),
      ("Moliyaviy natija va xarajatlarni nazorat qilish", M), ("Rahbarlar bilan yig'ilish o'tkazish", W), ("Brend va yangi filiallar bo'yicha qaror", N)]),
    ("ops_director", "Operatsion direktor", "mgmt", 2, "hq", "owner", "manager", "⚙️", 1, ["Operations Director", "Operatsion boshqaruvchi"],
     "Barcha filiallar bir xil standart bo'yicha, uzluksiz va foydali ishlashini ta'minlaydi.",
     [("Filial menejerlari ishini nazorat qilish", D), ("Filiallarda audit va standartlarga rioyani tekshirish", W),
      ("SOP va checklistlarni yangilash", M), ("KPI past filial bilan tuzatish rejasini tuzish", W), ("Muammo va shikoyatlarni hal qilish", N)]),
    ("brand_chef", "Brend-shef", "kitchen", 2, "hq", "owner", "manager", "👨‍🍳", 1, ["Bosh oshpaz", "Brand Chef", "Shef"],
     "Barcha filiallarda taom ta'mi, ko'rinishi va tannarxi bir xil bo'lishi uchun javobgar.",
     [("Tex-karta va retseptlarni tasdiqlash", N), ("Yangi taomlarni ishlab chiqish", M), ("Oshxonalarda sifat va gigiyenani tekshirish", W),
      ("Food cost va chiqindini nazorat qilish", W), ("Oshpazlarni o'qitish", M)]),
    ("hr_manager", "HR menejer", "hr", 2, "hq", "owner", "manager", "🧑‍💼", 1, ["HR", "Kadrlar bo'limi"],
     "Kerakli odamni topish, o'qitish va ushlab qolish uchun javobgar.",
     [("Vakansiya e'lon qilish va nomzodlar bilan suhbat", N), ("Yangi xodimni ishga moslashtirish (onboarding)", N),
      ("Trening va testlar bajarilishini kuzatish", W), ("Davomat va oylik hisobini tekshirish", M), ("Xodimlar kayfiyati va ketishini tahlil qilish", M)]),
    ("marketing", "Marketolog", "marketing", 2, "hq", "owner", "marketer", "📣", 1, ["Marketing menejer", "Marketing"],
     "Yangi mijoz jalb qilish va eski mijozni qaytarish uchun javobgar.",
     [("Telegram kanal va Instagram postlarini tayyorlash", D), ("Aksiya va bayram takliflarini rejalash", M),
      ("Bonus tizimi va mijozlar bazasini tahlil qilish", W), ("Reklama natijasini hisoblash", M)]),
    ("accountant", "Buxgalter", "finance", 2, "hq", "owner", "accountant", "💰", 1, ["Hisobchi", "Finance"],
     "Pul harakati, xarajat va soliqlar to'g'ri hisoblanishi uchun javobgar.",
     [("Kunlik kassa va to'lovlarni solishtirish", D), ("Xarajatlarni kiritish va tasdiqlash", D), ("Oylik hisobi va to'lovi", M),
      ("P&L va foyda hisobotini tayyorlash", M), ("Soliq hisobotlari", M)]),
    ("supply", "Ta'minot menejeri", "supply", 2, "hq", "ops_director", "accountant", "🚚", 1, ["Zakupshik", "Ta'minotchi", "Supply"],
     "Mahsulotlar kerakli vaqtda, sifatli va arzon narxda kelishi uchun javobgar.",
     [("Xarid rejasini tuzish (ombor → Xarid rejasi)", D), ("Yetkazib beruvchilardan narx so'rash va solishtirish", W),
      ("Kelgan mahsulot sifatini tekshirish", D), ("Bayram oldidan zaxira qilish", N)]),
    ("call_operator", "Call-operator", "hall", 5, "hq", "ops_director", "cashier", "🎧", 1, ["Call operator", "Operator"],
     "Telefon va Telegram orqali buyurtma va bronlarni tez va xushmuomala qabul qiladi.",
     [("Qo'ng'iroq va xabarlarga 1 daqiqada javob berish", S), ("Buyurtma va bronni tizimga kiritish", S), ("Shikoyatni menejerga yetkazish", N)]),
    ("branch_manager", "Filial menejeri", "mgmt", 3, "branch", "ops_director", "manager", "🏪", 1, ["Menejer", "Filial manager", "Administrator"],
     "Filialning kundalik ishi, xizmat sifati, savdosi va KPI natijasi uchun javobgar.",
     [("Filialni ochish va yopish checklistini tekshirish", D), ("Xodimlar davomati va smena jadvali", D), ("Kassa va naqd pulni tekshirish", D),
      ("Oshxona va zal standartlarini nazorat qilish", D), ("Ombor qoldig'i va xarid so'rovi", D), ("Mijoz shikoyatlarini hal qilish", N),
      ("Haftalik savdo va KPI tahlili", W)]),
    ("shift_manager", "Smena menejeri", "mgmt", 4, "branch", "branch_manager", "manager", "⏱️", 2, ["Smena boshlig'i", "Shift manager"],
     "Smena davomida ish tez, toza va standart bo'yicha bo'lishini ta'minlaydi.",
     [("Smenani qabul qilish va topshirish", S), ("Xodimlarni joylarga taqsimlash", S), ("Buyurtma kechikishini kuzatish", S),
      ("Smena oxirida kassa va tozalikni tekshirish", S)]),
    ("cook", "Oshpaz", "kitchen", 5, "branch", "shift_manager", "cook", "🍳", 3, ["Povar", "Cook"],
     "Taomlarni tex-karta bo'yicha, o'z vaqtida va gigiyena qoidalariga rioya qilib tayyorlaydi.",
     [("Ish joyini tayyorlash va mahsulotni tekshirish", S), ("Taomni tex-karta bo'yicha tayyorlash", S),
      ("Muzlatkich haroratini yozish", S), ("Ish joyini tozalash va yopish", S)]),
    ("cook_helper", "Oshpaz yordamchisi", "kitchen", 5, "branch", "shift_manager", "cook", "🥕", 2, ["Yordamchi oshpaz", "Kuxnya yordamchisi"],
     "Oshpazga yarim tayyor mahsulot va toza idish bilan yordam beradi.",
     [("Sabzavot va go'shtni tozalash, to'g'rash", S), ("Idish-tovoqni yuvish", S), ("Mahsulotlarni muddati bo'yicha joylash", S)]),
    ("cashier", "Kassir", "cash", 5, "branch", "shift_manager", "cashier", "💵", 2, ["Kassa", "Cashier"],
     "Buyurtmani to'g'ri qabul qiladi, to'lovni oladi va kassani aniq topshiradi.",
     [("Smenani ochish va boshlang'ich pulni sanash", S), ("Buyurtma va to'lovni kassada rasmiylashtirish", S),
      ("Bonus kartasini taklif qilish", S), ("Smena oxirida kassani topshirish", S)]),
    ("waiter", "Ofitsiant", "hall", 5, "branch", "shift_manager", "waiter", "🧑‍🍳", 4, ["Offitsiant", "Waiter"],
     "Mehmonni xushmuomala kutib oladi, buyurtmani tez qabul qiladi va stolni toza saqlaydi.",
     [("Stollarni tayyorlash", S), ("Mehmonga 2 daqiqada menyu berish", S), ("Buyurtmani kassaga kiritish", S), ("Stolni yig'ishtirish", S)]),
    ("hostess", "Xostes", "hall", 5, "branch", "shift_manager", "waiter", "🙋", 1, ["Hostes", "Administrator zal"],
     "Mehmonni eshikda kutib oladi, joy va bronlarni boshqaradi.",
     [("Mehmonni kutib olish va stolga olib borish", S), ("Bron va navbatni boshqarish", S), ("Kutish vaqtini mehmonga aytish", S)]),
    ("storekeeper", "Omborchi", "supply", 5, "branch", "branch_manager", "", "📦", 1, ["Sklad", "Ombor mudiri"],
     "Mahsulot kirimi, saqlanishi va qoldig'i to'g'ri bo'lishi uchun javobgar.",
     [("Kirimni tekshirish va kiritish", D), ("Mahsulot muddatini tekshirish", D), ("Haftalik inventarizatsiya", W)]),
    ("cleaner", "Tozalovchi", "service", 5, "branch", "shift_manager", "", "🧹", 1, ["Farrosh", "Uborshitsa"],
     "Zal, oshxona va hojatxona doim toza bo'lishini ta'minlaydi.",
     [("Zal va hojatxonani tozalash (grafik bo'yicha)", S), ("Axlatni chiqarish", S), ("Tozalash jurnalini to'ldirish", S)]),
]
