# Generated by Django 5.1.15 on 2026-09-19 18:48

import simple_history.models
from django.db import migrations, models

import modules.cms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalSiteSection",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hero", "Bosh bo'lim (hero)"),
                            ("menu", "Taomnoma"),
                            ("bonus", "Bonus tizimi"),
                            ("branches", "Filiallar"),
                            ("delivery", "Yetkazib berish"),
                            ("gallery", "Galereya"),
                            ("text", "Matn / e'lon"),
                            ("contact", "Aloqa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.JSONField(blank=True, default=dict)),
                ("props", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical site section",
                "verbose_name_plural": "historical site sections",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSiteSettings",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("title", models.CharField(default="", max_length=120)),
                ("tagline", models.JSONField(blank=True, default=dict)),
                ("logo", models.TextField(blank=True, max_length=100)),
                ("favicon", models.TextField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "telegram",
                    models.CharField(
                        blank=True, help_text="@bot yoki t.me havola", max_length=64
                    ),
                ),
                ("instagram", models.CharField(blank=True, max_length=64)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("languages", models.JSONField(default=list)),
                ("default_language", models.CharField(default="uz", max_length=5)),
                ("theme", models.JSONField(default=modules.cms.models.default_theme)),
                ("seo", models.JSONField(blank=True, default=dict)),
                ("delivery", models.JSONField(blank=True, default=dict)),
                ("custom_css", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Sayt sozlamalari",
                "verbose_name_plural": "historical Sayt sozlamalaris",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="media/%Y/%m/")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Rasm"),
                            ("video", "Video"),
                            ("file", "Fayl"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "folder",
                    models.CharField(db_index=True, default="umumiy", max_length=60),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("alt", models.CharField(blank=True, max_length=160)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("uploaded_by", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hero", "Bosh bo'lim (hero)"),
                            ("menu", "Taomnoma"),
                            ("bonus", "Bonus tizimi"),
                            ("branches", "Filiallar"),
                            ("delivery", "Yetkazib berish"),
                            ("gallery", "Galereya"),
                            ("text", "Matn / e'lon"),
                            ("contact", "Aloqa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.JSONField(blank=True, default=dict)),
                ("props", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="", max_length=120)),
                ("tagline", models.JSONField(blank=True, default=dict)),
                ("logo", models.ImageField(blank=True, upload_to="site/")),
                ("favicon", models.ImageField(blank=True, upload_to="site/")),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "telegram",
                    models.CharField(
                        blank=True, help_text="@bot yoki t.me havola", max_length=64
                    ),
                ),
                ("instagram", models.CharField(blank=True, max_length=64)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("languages", models.JSONField(default=list)),
                ("default_language", models.CharField(default="uz", max_length=5)),
                ("theme", models.JSONField(default=modules.cms.models.default_theme)),
                ("seo", models.JSONField(blank=True, default=dict)),
                ("delivery", models.JSONField(blank=True, default=dict)),
                ("custom_css", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sayt sozlamalari",
            },
        ),
    ]
