# Generated by Django 5.1.15 on 2026-09-26 23:42

import modules.forecast.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="tizim bayrami kodi (navruz, hayit…); qo'lda qo'shilganda bo'sh",
                        max_length=40,
                    ),
                ),
                ("name", models.JSONField(default=modules.forecast.models.empty_i18n)),
                ("date", models.DateField(db_index=True)),
                (
                    "days",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="necha kun davom etadi"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("official", "Davlat bayrami"),
                            ("religious", "Diniy bayram"),
                            ("commercial", "Tijoriy kun"),
                            ("season", "Mavsum"),
                            ("local", "O'zimizniki"),
                        ],
                        default="official",
                        max_length=12,
                    ),
                ),
                (
                    "uplift_percent",
                    models.IntegerField(
                        default=20,
                        help_text="kutilayotgan savdo o'zgarishi, % (manfiy ham bo'lishi mumkin)",
                    ),
                ),
                (
                    "prep_days",
                    models.PositiveSmallIntegerField(
                        default=7, help_text="necha kun oldin ogohlantirish"
                    ),
                ),
                (
                    "is_approx",
                    models.BooleanField(
                        default=False,
                        help_text="sana taxminiy (hayitlar — Diniy idora e'lonidan keyin aniqlanadi)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=240)),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="tayyorgarlik vazifasi ochilgan vaqt",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="WeatherDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("t_max", models.FloatField(default=0)),
                ("t_min", models.FloatField(default=0)),
                ("precip_mm", models.FloatField(default=0)),
                ("precip_prob", models.PositiveSmallIntegerField(default=0)),
                ("wind", models.FloatField(default=0, help_text="km/soat")),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="WMO ob-havo kodi"
                    ),
                ),
                ("source", models.CharField(default="open-meteo", max_length=20)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
