# Generated by Django 5.1.15 on 2026-09-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("payme", "Payme"), ("click", "Click")], max_length=8
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="Payme transaction id / Click click_trans_id",
                        max_length=64,
                    ),
                ),
                ("amount", models.BigIntegerField(help_text="so'm")),
                (
                    "state",
                    models.SmallIntegerField(
                        default=1,
                        help_text="Payme holati; Click: 1 prepare, 2 complete, -1 bekor",
                    ),
                ),
                ("reason", models.SmallIntegerField(blank=True, null=True)),
                (
                    "create_time",
                    models.BigIntegerField(default=0, help_text="ms (Payme)"),
                ),
                ("perform_time", models.BigIntegerField(default=0)),
                ("cancel_time", models.BigIntegerField(default=0)),
                (
                    "prepare_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="Click merchant_prepare_id", null=True
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
