# Generated by Django 5.1.15 on 2026-09-20 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="pos.order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("provider", "external_id")},
        ),
    ]
