# Generated by Django 5.1.15 on 2026-09-20 13:51

import django.db.models.deletion
import django.utils.timezone
import modules.inventory.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.JSONField(default=modules.inventory.models.empty_i18n)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Go'sht, Sabzavot, Sut mahsulotlari, Quruq…",
                        max_length=60,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "kg"), ("l", "litr"), ("dona", "dona")],
                        default="kg",
                        max_length=5,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="so'm / bazaviy birlik (kg, l, dona)",
                        max_digits=14,
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="qoldiq, bazaviy birlikda",
                        max_digits=14,
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="shu miqdordan kam bo'lsa — ogohlantirish",
                        max_digits=14,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "id"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalRecipe",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "yield_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="necha porsiya chiqadi",
                        max_digits=8,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="tayyorlash tartibi (oshpaz uchun)"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="1 porsiya tannarxi, so'm (avtomatik)",
                        max_digits=14,
                    ),
                ),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical recipe",
                "verbose_name_plural": "historical recipes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField(editable=False)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "is_posted",
                    models.BooleanField(default=True, help_text="omborga o'tkazilgan"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="bazaviy birlikda (kg/l/dona)",
                        max_digits=14,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="so'm / bazaviy birlik",
                        max_digits=14,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_lines",
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.purchase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "yield_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="necha porsiya chiqadi",
                        max_digits=8,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="tayyorlash tartibi (oshpaz uchun)"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="1 porsiya tannarxi, so'm (avtomatik)",
                        max_digits=14,
                    ),
                ),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecipeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="mayda birlikda: g / ml / dona",
                        max_digits=12,
                    ),
                ),
                (
                    "waste_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="tozalash/pishirish chiqindisi, %",
                        max_digits=5,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_lines",
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("purchase", "Kirim"),
                            ("sale", "Savdo"),
                            ("waste", "Chiqindi / yaroqsiz"),
                            ("adjust", "Inventarizatsiya"),
                            ("transfer", "Filialga o'tkazish"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="+ kirim, − chiqim (bazaviy birlik)",
                        max_digits=14,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True, help_text="Kirim #12, Buyurtma #345…", max_length=60
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.branch",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.ingredient",
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="ingredient",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingredients",
                to="inventory.supplier",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalIngredient",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.JSONField(default=modules.inventory.models.empty_i18n)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Go'sht, Sabzavot, Sut mahsulotlari, Quruq…",
                        max_length=60,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "kg"), ("l", "litr"), ("dona", "dona")],
                        default="kg",
                        max_length=5,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="so'm / bazaviy birlik (kg, l, dona)",
                        max_digits=14,
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="qoldiq, bazaviy birlikda",
                        max_digits=14,
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="shu miqdordan kam bo'lsa — ogohlantirish",
                        max_digits=14,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ingredient",
                "verbose_name_plural": "historical ingredients",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
