# Generated by Django 5.1.15 on 2026-09-27 11:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_normalize_phones"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bazaar", "Dehqon bozori"),
                            ("wholesale", "Ulgurji baza"),
                            ("producer", "Ishlab chiqaruvchi ombori"),
                            ("cashcarry", "Supermarket / Cash&Carry"),
                            ("online", "Onlayn / yetkazib berish"),
                        ],
                        default="bazaar",
                        max_length=10,
                    ),
                ),
                ("city", models.CharField(default="Toshkent", max_length=60)),
                ("district", models.CharField(blank=True, max_length=80)),
                ("address", models.CharField(blank=True, max_length=200)),
                (
                    "landmark",
                    models.CharField(blank=True, help_text="mo'ljal", max_length=160),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "hours",
                    models.CharField(
                        blank=True, help_text="05:00–18:00", max_length=80
                    ),
                ),
                (
                    "days",
                    models.CharField(
                        blank=True,
                        help_text="har kuni / dushanbadan tashqari",
                        max_length=80,
                    ),
                ),
                ("categories", models.JSONField(blank=True, default=list)),
                (
                    "tips",
                    models.TextField(
                        blank=True,
                        help_text="bozorchi uchun maslahat: qachon borish, qayerda arzon, parking…",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_builtin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField(editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("sent", "Yuborildi"),
                            ("confirmed", "Tasdiqlandi"),
                            ("received", "Qabul qilindi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("total", models.BigIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "purchase_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="inventory.Purchase (omborga kirim)",
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1–5: sifat va o'z vaqtida", null=True
                    ),
                ),
                ("rating_note", models.CharField(blank=True, max_length=200)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("price", models.BigIntegerField(default=0)),
                (
                    "received_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="procurement.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.BigIntegerField()),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd"),
                            ("card", "Karta"),
                            ("transfer", "O'tkazma"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=160)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="procurement.order",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("company", "Kompaniya"),
                            ("bazaar", "Bozor sotuvchisi"),
                            ("farmer", "Fermer"),
                            ("producer", "Ishlab chiqaruvchi"),
                        ],
                        default="company",
                        max_length=10,
                    ),
                ),
                ("categories", models.JSONField(blank=True, default=list)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                (
                    "telegram",
                    models.CharField(
                        blank=True, help_text="@username yoki telefon", max_length=64
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200)),
                ("delivers", models.BooleanField(default=False)),
                (
                    "min_order",
                    models.CharField(
                        blank=True, help_text="masalan: 20 kg dan", max_length=60
                    ),
                ),
                (
                    "terms",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd, darhol"),
                            ("transfer", "O'tkazma"),
                            ("credit", "Nasiya (keyin to'lash)"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("credit_days", models.PositiveSmallIntegerField(default=0)),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppliers",
                        to="procurement.market",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField(editable=False, unique=True)),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Rejada"),
                            ("active", "Bozorda"),
                            ("closed", "Hisob yopildi"),
                            ("cancelled", "Bekor"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "advance",
                    models.BigIntegerField(
                        default=0, help_text="bozorchiga berilgan pul"
                    ),
                ),
                (
                    "returned",
                    models.BigIntegerField(
                        default=0, help_text="bozordan keyin qaytarilgan pul"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=240)),
                ("overhead_to_cost", models.BooleanField(default=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("purchase_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.branch",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="procurement.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="TripExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("taxi", "Taksi / transport"),
                            ("porter", "Hammol / yuk ortish"),
                            ("fuel", "Yoqilg'i"),
                            ("fee", "Bozor to'lovi / joy"),
                            ("pack", "Qop, paket, idish"),
                            ("food", "Ovqat"),
                            ("other", "Boshqa"),
                        ],
                        default="taxi",
                        max_length=8,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("note", models.CharField(blank=True, max_length=160)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="procurement/receipts/%Y/%m/"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="procurement.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TripItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("unit", models.CharField(default="kg", max_length=8)),
                (
                    "planned_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="ro'yxatdagi (reja)",
                        max_digits=12,
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="haqiqatda olingan",
                        max_digits=12,
                    ),
                ),
                (
                    "price",
                    models.BigIntegerField(default=0, help_text="1 birlik narxi"),
                ),
                ("total", models.BigIntegerField(default=0)),
                ("seller", models.CharField(blank=True, max_length=120)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="procurement/receipts/%Y/%m/"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.BigIntegerField(help_text="so'm / bazaviy birlik")),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Qo'lda"),
                            ("order", "Buyurtma"),
                            ("trip", "Bozorlik"),
                        ],
                        default="manual",
                        max_length=8,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prices",
                        to="procurement.market",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["ingredient", "date"],
                        name="procurement_ingredi_28128e_idx",
                    )
                ],
            },
        ),
    ]
