# Generated by Django 5.1.15 on 2026-09-27 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "Bo'sh"),
                            ("wait", "Ovozli xabar kutilmoqda"),
                            ("confirm", "Tasdiq kutilmoqda"),
                            ("busy", "Bajarilmoqda"),
                        ],
                        default="idle",
                        max_length=8,
                    ),
                ),
                (
                    "pending",
                    models.TextField(
                        blank=True, help_text="tasdiq kutayotgan buyruq matni"
                    ),
                ),
                (
                    "confirm_msg_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="«Tasdiqlaysizmi?» xabari — tugmalarni olib tashlash uchun",
                        null=True,
                    ),
                ),
                ("base_url", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AiLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        default="telegram",
                        help_text="telegram | panel | morning",
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        default="ask",
                        help_text="ask | voice | report | test",
                        max_length=10,
                    ),
                ),
                ("question", models.TextField(blank=True)),
                ("answer", models.TextField(blank=True)),
                ("ok", models.BooleanField(default=True)),
                ("error", models.CharField(blank=True, max_length=240)),
                ("model", models.CharField(blank=True, max_length=60)),
                (
                    "calls",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="AI'ga nechta so'rov ketdi"
                    ),
                ),
                ("tokens", models.PositiveIntegerField(default=0)),
                ("ms", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ok", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "user")},
            },
        ),
    ]
