# Generated by Django 5.1.15 on 2026-09-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aichat",
            name="run",
            field=models.CharField(
                blank=True,
                help_text="joriy ish kaliti — «⏹ To'xtatish» bosilsa almashadi va ish to'xtaydi",
                max_length=32,
            ),
        ),
    ]
