# Generated by Django 5.1.15 on 2026-09-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_chat_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="aichat",
            name="mode",
            field=models.CharField(
                default="local",
                help_text="local — restoran; web — restoran + internet (🌐 Global qidiruv)",
                max_length=8,
            ),
        ),
    ]
