# Generated by Django 5.1.15 on 2026-09-29 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_chat_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=24)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Tasdiq kutilmoqda"),
                            ("waiting", "Xodim javobi kutilmoqda"),
                            ("ready", "Tasdiq kutilmoqda"),
                            ("done", "Bajarildi"),
                            ("cancelled", "Bekor qilindi"),
                            ("expired", "Muddati o'tdi"),
                            ("failed", "Bajarilmadi"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        default="panel",
                        help_text="telegram | panel — tasdiq qayerga so'raladi",
                        max_length=10,
                    ),
                ),
                ("result", models.CharField(blank=True, max_length=400)),
                (
                    "tg_msgs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[[chat_id, message_id]] — tasdiq xabarlari (tugmalarni yangilash uchun)",
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
