# Generated by Django 5.1.15 on 2026-09-20 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('guests', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('waiting', 'Navbatda'), ('called', 'Chaqirildi'), ('seated', "O'tirdi"), ('left', 'Ketdi')], db_index=True, default='waiting', max_length=8)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_minutes', models.PositiveSmallIntegerField(default=15, help_text='aytilgan kutish vaqti')),
                ('note', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name_plural': 'waitlist',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('guests', models.PositiveSmallIntegerField(default=2)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=90)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlandi'), ('seated', "O'tirdi"), ('done', 'Tugadi'), ('cancelled', 'Bekor'), ('no_show', 'Kelmadi')], db_index=True, default='new', max_length=10)),
                ('source', models.CharField(default='phone', help_text='phone | hall | site | telegram', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('occasion', models.CharField(blank=True, help_text="tug'ilgan kun, uchrashuv...", max_length=40)),
                ('deposit', models.BigIntegerField(default=0, help_text="oldindan to'lov (so'm)")),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
    ]
