# Generated by Django 5.1.15 on 2026-09-20 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='tables.table'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='tables.zone'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist', to='tables.table'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['starts_at', 'status'], name='reservation_starts__4e159e_idx'),
        ),
    ]
