# Generated by Django 5.1.15 on 2026-09-19 18:48

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "price_per_branch",
                    models.BigIntegerField(default=0, help_text="so'm / filial / oy"),
                ),
                ("max_branches", models.PositiveIntegerField(default=1)),
                ("max_devices", models.PositiveIntegerField(default=2)),
                (
                    "allowed_modules",
                    models.JSONField(
                        default=list,
                        help_text="modul kodlari ro'yxati; ['*'] = hammasi",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "slug",
                    models.SlugField(
                        help_text="subdomen: <slug>.restopos.uz", unique=True
                    ),
                ),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            ("fast_food", "Fast-food"),
                            ("cafe", "Kafe"),
                            ("restaurant", "Restoran"),
                            ("cloud_kitchen", "Cloud kitchen"),
                        ],
                        default="fast_food",
                        max_length=32,
                    ),
                ),
                (
                    "enabled_modules",
                    models.JSONField(default=list, help_text="yoqilgan modul kodlari"),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text="tenant darajasidagi sozlamalar (tillar, valyuta, soliq rejimi...)",
                    ),
                ),
                ("owner_phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="public.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="public.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
