# Generated by Django 5.1.15 on 2026-09-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_hq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformstaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("founder", "Asoschi (founder)"),
                    ("developer", "Dasturchi (developer)"),
                    ("superadmin", "Bosh administrator"),
                    ("support", "Texnik yordam"),
                    ("sales", "Sotuv"),
                    ("finance", "Moliya"),
                ],
                default="support",
                max_length=12,
            ),
        ),
    ]
