# Generated by Django 5.1.15 on 2026-10-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_access_v33"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(max_length=40)),
                (
                    "business",
                    models.CharField(
                        blank=True,
                        help_text="restoran nomi / turi / filiallar",
                        max_length=160,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("source", models.CharField(default="ai_chat", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("contacted", "Bog'lanildi"),
                            ("won", "Mijoz bo'ldi"),
                            ("lost", "Rad etdi"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SiteOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="$", max_length=8)),
                (
                    "base_price",
                    models.PositiveIntegerField(
                        default=100, help_text="Dastur — oyiga"
                    ),
                ),
                (
                    "ai_price",
                    models.PositiveIntegerField(
                        default=150, help_text="Dastur + AI Kotib — oyiga"
                    ),
                ),
                (
                    "price_note",
                    models.CharField(
                        default="bitta restoran uchun, oyiga", max_length=120
                    ),
                ),
                ("trial_days", models.PositiveIntegerField(default=30)),
                (
                    "free_setup",
                    models.BooleanField(
                        default=True, help_text="Ulash va sozlash bepul (aksiya)"
                    ),
                ),
                (
                    "setup_note",
                    models.CharField(
                        default="Hozir ulash, menyuni kiritish va xodimlarni o'rgatish — bepul",
                        max_length=200,
                    ),
                ),
                (
                    "includes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="narx ichida nimalar bor (ro'yxat)",
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="masalan: restopos_uz (@ siz)",
                        max_length=60,
                    ),
                ),
                (
                    "ai_chat",
                    models.BooleanField(
                        default=True, help_text="Saytda AI maslahatchi yoqilgan"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
