# Generated by Django 5.1.15 on 2026-10-04 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0004_site_offer_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteoffer",
            name="ai_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Gemini API kaliti (saytdagi AI uchun); bo'sh — .env yoki restoran kaliti",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.CharField(max_length=40, unique=True)),
                ("ip", models.CharField(blank=True, max_length=64)),
                ("ua", models.CharField(blank=True, max_length=200)),
                (
                    "messages",
                    models.JSONField(
                        blank=True, default=list, help_text="[{role: me|ai, text, at}]"
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chats",
                        to="public.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
