# Generated by Django 5.1.15 on 2026-10-04 03:31

import django.db.models.deletion
from django.db import migrations, models


def fill_due(apps, schema_editor):
    from datetime import timedelta
    Ticket = apps.get_model("public", "Ticket")
    hours = {"critical": 4, "high": 24, "normal": 72, "low": 168}
    for t in Ticket.objects.filter(due_at__isnull=True):
        t.due_at = t.created_at + timedelta(hours=hours.get(t.priority, 72))
        t.save(update_fields=["due_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0006_offer_ru_lead_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="UZS", max_length=3),
        ),
        migrations.AddField(
            model_name="invoice",
            name="method",
            field=models.CharField(
                blank=True,
                help_text="naqd / karta / bank / payme / click",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="tenant",
            name="district",
            field=models.CharField(
                blank=True, default="", help_text="tuman / shahar", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="limits",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenant",
            name="region",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="viloyat / Toshkent shahri",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="due_at",
            field=models.DateTimeField(
                blank=True, help_text="hal qilish muddati (SLA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="kind",
            field=models.CharField(
                choices=[
                    ("bug", "Xato (ishlamayapti)"),
                    ("question", "Savol / yordam"),
                    ("feature", "Taklif / yangi funksiya"),
                    ("task", "Ichki vazifa"),
                ],
                default="bug",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sort",
            field=models.FloatField(
                default=0, help_text="doskadagi tartib (kichigi — yuqorida)"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="bo'sh — ichki vazifa",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="public.tenant",
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("signed_at", models.DateField(blank=True, null=True)),
                (
                    "tariff",
                    models.CharField(
                        choices=[("base", "Dastur"), ("ai", "Dastur + AI Kotib")],
                        default="base",
                        max_length=8,
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=100, help_text="oylik narx (shartnoma bo'yicha)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "$"), ("UZS", "so'm")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "included_branches",
                    models.PositiveIntegerField(
                        default=1, help_text="narx ichidagi filiallar"
                    ),
                ),
                (
                    "extra_branch_price",
                    models.PositiveIntegerField(
                        default=0, help_text="har qo'shimcha filial uchun oyiga"
                    ),
                ),
                (
                    "billing_day",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="har oy nechanchi sanada to'laydi (1–28)"
                    ),
                ),
                (
                    "paid_from",
                    models.DateField(
                        blank=True,
                        help_text="shu sanadan pullik (undan oldin — bepul davr)",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="yuridik nom (MChJ / YaTT)",
                        max_length=160,
                    ),
                ),
                ("inn", models.CharField(blank=True, help_text="STIR", max_length=20)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "terms",
                    models.TextField(
                        blank=True,
                        help_text="maxsus kelishuvlar (chegirma, qo'shimcha ish, muddatlar)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="mas'ul menejer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="public.platformstaff",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="public.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(fill_due, migrations.RunPython.noop),
    ]
