# Generated by Django 5.1.15 on 2026-09-20 17:36

import django.db.models.deletion
import modules.kds.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.JSONField(default=modules.kds.models.empty_i18n)),
                ('color', models.CharField(default='#0F6E63', max_length=9)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kds_stations', to='core.branch')),
                ('categories', models.ManyToManyField(blank=True, related_name='kds_stations', to='catalog.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('cooking', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('served', 'Berildi'), ('cancelled', 'Bekor')], db_index=True, default='new', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('cook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kds_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_tickets', to='pos.order')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='kds.station')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('order', 'station')},
            },
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('is_done', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.orderitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kds.ticket')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
