# Generated by Django 5.1.15 on 2026-09-23 23:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="['cook', 'waiter'] — bo'sh bo'lsa hamma",
                    ),
                ),
                (
                    "positions",
                    models.JSONField(
                        blank=True, default=list, help_text="hr.Position id'lari"
                    ),
                ),
                (
                    "user_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="aniq xodimlar (User.id satr)",
                    ),
                ),
                (
                    "everyone",
                    models.BooleanField(default=False, help_text="barcha xodimlar"),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Oshxona, Zal, Gigiyena…", max_length=60
                    ),
                ),
                ("cover", models.ImageField(blank=True, upload_to="training/covers/")),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "due_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="biriktirilgandan keyin necha kunda tugatish kerak (0 — muddatsiz)",
                    ),
                ),
                ("pass_score", models.PositiveSmallIntegerField(default=80)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "certificate",
                    models.BooleanField(
                        default=True, help_text="tugatganda sertifikat beriladi"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="['cook', 'waiter'] — bo'sh bo'lsa hamma",
                    ),
                ),
                (
                    "positions",
                    models.JSONField(
                        blank=True, default=list, help_text="hr.Position id'lari"
                    ),
                ),
                (
                    "user_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="aniq xodimlar (User.id satr)",
                    ),
                ),
                (
                    "everyone",
                    models.BooleanField(default=False, help_text="barcha xodimlar"),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        help_text="namuna video yoki rasm",
                        upload_to="training/assignments/",
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("requires_proof", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        help_text="tekshiradigan mas'ul",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="training.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True, help_text="Tavsif / dars matni")),
                (
                    "checklist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Dars mazmuni bandlari: ['Kerakli mahsulotlar', ...]",
                    ),
                ),
                ("video", models.FileField(blank=True, upload_to="training/videos/")),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="YouTube yoki boshqa havola"),
                ),
                ("image", models.ImageField(blank=True, upload_to="training/images/")),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="video davomiyligi (brauzer aniqlaydi)"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="training.course",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LessonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="training/files/")),
                ("title", models.CharField(blank=True, max_length=160)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="training.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(default=0, help_text="0 — cheklovsiz"),
                ),
                (
                    "pass_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 — kurs bali ishlatiladi"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 — cheksiz"
                    ),
                ),
                ("shuffle", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="training.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="bo'sh — kurs yakuniy testi",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="training.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="training/questions/"),
                ),
                (
                    "options",
                    models.JSONField(
                        default=list, help_text='[{"id": "a", "text": "55°C"}, ...]'
                    ),
                ),
                (
                    "correct",
                    models.JSONField(
                        default=list,
                        help_text="[\"c\"] — bittadan ko'p bo'lsa ko'p tanlovli",
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="training.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("question_ids", models.JSONField(default=list)),
                (
                    "answers",
                    models.JSONField(default=dict, help_text='{"<qid>": ["c"]}'),
                ),
                ("correct_count", models.PositiveSmallIntegerField(default=0)),
                ("total", models.PositiveSmallIntegerField(default=0)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="training.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="['cook', 'waiter'] — bo'sh bo'lsa hamma",
                    ),
                ),
                (
                    "positions",
                    models.JSONField(
                        blank=True, default=list, help_text="hr.Position id'lari"
                    ),
                ),
                (
                    "user_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="aniq xodimlar (User.id satr)",
                    ),
                ),
                (
                    "everyone",
                    models.BooleanField(default=False, help_text="barcha xodimlar"),
                ),
                ("title", models.CharField(max_length=160)),
                ("category", models.CharField(blank=True, max_length=60)),
                ("body", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="rasm, video yoki PDF",
                        upload_to="training/standards/",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_standards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Bajarilmagan"),
                            ("submitted", "Tekshiruvda"),
                            ("approved", "Qabul qilindi"),
                            ("rejected", "Qaytarildi"),
                        ],
                        default="todo",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="training.assignment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("assignment", "user")},
            },
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="training/proofs/%Y/%m/")),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="training.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Biriktirilgan"),
                            ("in_progress", "O'qiyapti"),
                            ("completed", "Tugatgan"),
                        ],
                        default="assigned",
                        max_length=12,
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(default=0, help_text="0–100"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("certificate_no", models.CharField(blank=True, max_length=24)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="training.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="training.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "unique_together": {("course", "user")},
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watched_seconds",
                    models.FloatField(
                        default=0,
                        help_text="haqiqatda ko'rilgan soniyalar (o'tkazib yuborilganlar hisobga kirmaydi)",
                    ),
                ),
                (
                    "max_position",
                    models.FloatField(
                        default=0, help_text="videoda yetib borgan eng uzoq nuqta"
                    ),
                ),
                ("last_position", models.FloatField(default=0)),
                ("duration", models.FloatField(default=0)),
                ("percent", models.PositiveSmallIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "first_opened_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_beat_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="training.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "lesson")},
            },
        ),
        migrations.CreateModel(
            name="StandardAck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("acked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acks",
                        to="training.standard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_acks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("standard", "user", "version")},
            },
        ),
    ]
