# Generated by Django 5.1.15 on 2026-09-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_role_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="media_url",
            field=models.URLField(
                blank=True,
                help_text="yoki internetdagi video/rasm havolasi",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="cover_url",
            field=models.URLField(
                blank=True, help_text="yoki internetdagi rasm havolasi", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="yoki internetdagi rasm havolasi", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="lessonfile",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="fayl o'rniga internetdagi havola (Google Drive va h.k.)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="file_url",
            field=models.URLField(
                blank=True, help_text="yoki internetdagi havola", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="video davomiyligi (fayl/YouTube — brauzer aniqlaydi; Drive/Vimeo — admin yozadi)",
            ),
        ),
        migrations.AlterField(
            model_name="lessonfile",
            name="file",
            field=models.FileField(blank=True, upload_to="training/files/"),
        ),
    ]
