# Generated by Django 5.1.15 on 2026-09-20 13:51

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Oshxona, Zal, Kassa, Boshqaruv…",
                        max_length=60,
                    ),
                ),
                (
                    "default_salary_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Oylik stavka"),
                            ("hourly", "Soatbay"),
                            ("shift", "Smenabay"),
                            ("percent", "Savdodan %"),
                        ],
                        default="monthly",
                        max_length=8,
                    ),
                ),
                ("default_rate", models.BigIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hire_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("fire_date", models.DateField(blank=True, null=True)),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Oylik stavka"),
                            ("hourly", "Soatbay"),
                            ("shift", "Smenabay"),
                            ("percent", "Savdodan %"),
                        ],
                        default="monthly",
                        max_length=8,
                    ),
                ),
                (
                    "rate",
                    models.BigIntegerField(
                        default=0,
                        help_text="so'm: oylik / soat / smena; percent uchun — foiz×100 (2.5% = 250)",
                    ),
                ),
                ("pinfl", models.CharField(blank=True, max_length=14)),
                ("passport", models.CharField(blank=True, max_length=12)),
                (
                    "card_number",
                    models.CharField(
                        blank=True, help_text="oylik tushadigan karta", max_length=20
                    ),
                ),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="core.branch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hr.position",
                    ),
                ),
            ],
            options={
                "ordering": ["user__full_name"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "check_in",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="panel", max_length=12)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=120)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.branch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-check_in"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEmployee",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "hire_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("fire_date", models.DateField(blank=True, null=True)),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Oylik stavka"),
                            ("hourly", "Soatbay"),
                            ("shift", "Smenabay"),
                            ("percent", "Savdodan %"),
                        ],
                        default="monthly",
                        max_length=8,
                    ),
                ),
                (
                    "rate",
                    models.BigIntegerField(
                        default=0,
                        help_text="so'm: oylik / soat / smena; percent uchun — foiz×100 (2.5% = 250)",
                    ),
                ),
                ("pinfl", models.CharField(blank=True, max_length=14)),
                ("passport", models.CharField(blank=True, max_length=12)),
                (
                    "card_number",
                    models.CharField(
                        blank=True, help_text="oylik tushadigan karta", max_length=20
                    ),
                ),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical employee",
                "verbose_name_plural": "historical employees",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.DateField(db_index=True, help_text="oyning 1-sanasi"),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Oylik stavka"),
                            ("hourly", "Soatbay"),
                            ("shift", "Smenabay"),
                            ("percent", "Savdodan %"),
                        ],
                        max_length=8,
                    ),
                ),
                ("rate", models.BigIntegerField(default=0)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("shifts", models.PositiveIntegerField(default=0)),
                (
                    "sales_base",
                    models.BigIntegerField(
                        default=0, help_text="percent turi uchun savdo bazasi"
                    ),
                ),
                ("base", models.BigIntegerField(default=0)),
                ("bonus", models.BigIntegerField(default=0)),
                ("penalty", models.BigIntegerField(default=0)),
                ("advance", models.BigIntegerField(default=0)),
                ("total", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("approved", "Tasdiqlangan"),
                            ("paid", "To'langan"),
                        ],
                        default="draft",
                        max_length=8,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "employee__user__full_name"],
                "unique_together": {("employee", "period")},
            },
        ),
        migrations.CreateModel(
            name="ShiftPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("start", models.TimeField(default="09:00")),
                ("end", models.TimeField(default="18:00")),
                ("note", models.CharField(blank=True, max_length=120)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.branch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start"],
                "unique_together": {("employee", "date", "start")},
            },
        ),
    ]
