# Generated by Django 5.1.15 on 2026-09-25 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_normalize_phones"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="education",
            field=models.CharField(
                blank=True,
                help_text="masalan: Toshkent oshpazlik kolleji, 2019",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_name",
            field=models.CharField(
                blank=True,
                help_text="favqulodda aloqa: kim (ona, turmush o'rtog'i…)",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="fire_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(blank=True, help_text="m | f", max_length=1),
        ),
        migrations.AddField(
            model_name="employee",
            name="languages",
            field=models.JSONField(
                blank=True, default=list, help_text='["o\'zbek", "rus"]'
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="medical_book_until",
            field=models.DateField(
                blank=True, help_text="tibbiy daftarcha amal qilish muddati", null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="skills",
            field=models.JSONField(
                blank=True, default=list, help_text='["tandir", "kassa", "Excel"]'
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="qayerdan kelgan: vakansiya, tavsiya…",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="education",
            field=models.CharField(
                blank=True,
                help_text="masalan: Toshkent oshpazlik kolleji, 2019",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="emergency_name",
            field=models.CharField(
                blank=True,
                help_text="favqulodda aloqa: kim (ona, turmush o'rtog'i…)",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="fire_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="gender",
            field=models.CharField(blank=True, help_text="m | f", max_length=1),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="languages",
            field=models.JSONField(
                blank=True, default=list, help_text='["o\'zbek", "rus"]'
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="medical_book_until",
            field=models.DateField(
                blank=True, help_text="tibbiy daftarcha amal qilish muddati", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="skills",
            field=models.JSONField(
                blank=True, default=list, help_text='["tandir", "kassa", "Excel"]'
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="qayerdan kelgan: vakansiya, tavsiya…",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("birth_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=80)),
                (
                    "experience",
                    models.TextField(
                        blank=True, help_text="o'zi haqida / tajriba (erkin matn)"
                    ),
                ),
                (
                    "work_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"company": "", "position": "", "years": ""}]',
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"q": "...", "a": "...", "ok": true}]',
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="hr/candidates/")),
                ("resume", models.FileField(blank=True, upload_to="hr/resumes/")),
                (
                    "source",
                    models.CharField(
                        default="site",
                        help_text="site | telegram | manual | referral",
                        max_length=12,
                    ),
                ),
                ("tg_chat_id", models.BigIntegerField(blank=True, null=True)),
                ("tg_username", models.CharField(blank=True, max_length=64)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "Yangi ariza"),
                            ("screen", "Ko'rib chiqilmoqda"),
                            ("interview", "Suhbat"),
                            ("trial", "Sinov kuni"),
                            ("offer", "Taklif"),
                            ("hired", "Qabul qilindi"),
                            ("rejected", "Rad etildi"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "knocked_out",
                    models.BooleanField(
                        default=False, help_text="majburiy savolga mos javob bermagan"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=0, help_text="0–5 yulduz"),
                ),
                ("notes", models.TextField(blank=True)),
                ("interview_at", models.DateTimeField(blank=True, null=True)),
                ("interview_place", models.CharField(blank=True, max_length=160)),
                ("reject_reason", models.CharField(blank=True, max_length=200)),
                (
                    "stage_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "kind",
                    models.CharField(
                        default="note",
                        help_text="created | stage | note | message | interview",
                        max_length=16,
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=400)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="hr.application",
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("contract", "Mehnat shartnomasi"),
                            ("medbook", "Tibbiy daftarcha"),
                            ("passport", "Pasport nusxasi"),
                            ("diploma", "Diplom / sertifikat"),
                            ("other", "Boshqa"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("file", models.FileField(blank=True, upload_to="hr/docs/%Y/")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="fayl o'rniga havola (Google Drive va h.k.)",
                        max_length=500,
                    ),
                ),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.DateField(db_index=True, help_text="oyning 1-sanasi"),
                ),
                (
                    "scores",
                    models.JSONField(default=dict, help_text='{"discipline": 4, ...}'),
                ),
                ("strengths", models.CharField(blank=True, max_length=300)),
                ("improve", models.CharField(blank=True, max_length=300)),
                ("goals", models.CharField(blank=True, max_length=300)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="hr.employee",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "mood",
                    models.PositiveSmallIntegerField(help_text="1 — yomon … 4 — a'lo"),
                ),
                ("comment", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "attendance",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="hr.attendance",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=140)),
                (
                    "role_code",
                    models.CharField(
                        default="waiter",
                        help_text="qabul qilinganda beriladigan rol",
                        max_length=40,
                    ),
                ),
                (
                    "employment",
                    models.CharField(
                        default="full",
                        help_text="full | part | shift | intern",
                        max_length=20,
                    ),
                ),
                ("salary_from", models.BigIntegerField(default=0)),
                ("salary_to", models.BigIntegerField(default=0)),
                (
                    "salary_note",
                    models.CharField(
                        blank=True,
                        help_text="masalan: + choychaqa, bonus",
                        max_length=120,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True, help_text="2/2, 10:00–22:00", max_length=120
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("duties", models.JSONField(blank=True, default=list)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("image", models.ImageField(blank=True, upload_to="hr/vacancies/")),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube / Instagram / Drive",
                        max_length=500,
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="qo'shimcha havola (masalan, jamoa haqida)",
                        max_length=500,
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"text": "Kechki smenada ishlay olasizmi?", "type": "yesno", "must": "ha"}]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("open", "Ochiq"),
                            ("paused", "To'xtatilgan"),
                            ("closed", "Yopilgan"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=8,
                    ),
                ),
                ("closes_on", models.DateField(blank=True, null=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacancies",
                        to="core.branch",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacancies",
                        to="hr.position",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="vacancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="hr.vacancy",
            ),
        ),
        migrations.CreateModel(
            name="WorkHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=160)),
                ("position", models.CharField(blank=True, max_length=120)),
                (
                    "start",
                    models.CharField(
                        blank=True, help_text="2019-03 yoki 2019", max_length=20
                    ),
                ),
                (
                    "end",
                    models.CharField(
                        blank=True, help_text="bo'sh — hozirgacha", max_length=20
                    ),
                ),
                ("reason_left", models.CharField(blank=True, max_length=200)),
                (
                    "reference_phone",
                    models.CharField(
                        blank=True, help_text="tavsiya beruvchi telefon", max_length=20
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_history",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-start", "-id"],
            },
        ),
    ]
