# Generated by Django 5.1.15 on 2026-09-27 23:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_normalize_phones"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="role",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="100 Superadmin · 80 Bosh menejer · 60 Filial menejeri · 10 xodim",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="extra_permissions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Roldan tashqari shaxsiy ruxsatlar (masalan ['ai.use', 'inventory.view'])",
            ),
        ),
        migrations.CreateModel(
            name="LoginRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=10)),
                (
                    "secret",
                    models.CharField(
                        help_text="brauzerdagi so'rov kaliti (boshqa odam tokenni ololmasin)",
                        max_length=64,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=64)),
                ("device", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
