# Generated by Django 5.1.15 on 2026-09-28 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_role_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_invite",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Telegram taklif havolasi kodi (t.me/<bot>?start=inv_<kod>)",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_invite_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="oshsa — barcha qurilmalardagi kirishlar bekor bo'ladi",
            ),
        ),
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram tasdig'i"),
                            ("password", "Parol"),
                            ("code", "Bir martalik kod"),
                            ("switch", "Restoranlar orasida o'tish"),
                            ("support", "Platforma yordami"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=64)),
                ("device", models.CharField(blank=True, max_length=160)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
    ]
