# Generated by Django 5.1.15 on 2026-09-29 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("full_name", models.CharField(max_length=120)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="qaysi lavozimga / kim tavsiya qildi",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=10),
                ),
                ("telegram_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="telefon raqami Telegram orqali tasdiqlangan",
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="tasdiqlangach yaratilgan xodim",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
