# Generated by Django 5.1.15 on 2026-09-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_join_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="ro'yxatdan o'tishda o'ylagan paroli (hash) — tasdiqlangach shu parol bilan kiradi",
                max_length=128,
            ),
        ),
    ]
