# Generated by Django 5.1.15 on 2026-09-20 12:27

import django.db.models.deletion
import modules.tasks.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.JSONField(default=modules.tasks.models.empty_i18n)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("backlog", "Yangi"),
                            ("active", "Jarayonda"),
                            ("review", "Tekshiruvda"),
                            ("done", "Bajarildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("color", models.CharField(default="#6B6A63", max_length=9)),
                (
                    "wip_limit",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 = cheksiz; Kanban WIP chegarasi"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40)),
                ("color", models.CharField(default="#1F5FBF", max_length=9)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "number",
                    models.PositiveIntegerField(
                        editable=False,
                        help_text="#1238 — restoran ichida ketma-ket",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Zal, 3-stol / Oshxona / Ombor",
                        max_length=120,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Past"),
                            ("normal", "O'rta"),
                            ("high", "Muhim"),
                            ("urgent", "Shoshilinch"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=8,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Qo'lda"),
                            ("issue", "Muammo (xodim aniqladi)"),
                            ("recurring", "Takroriy"),
                            ("checklist", "Checklist"),
                            ("system", "Tizim"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="tekshiruvga topshirilgan vaqt", null=True
                    ),
                ),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.BigIntegerField(
                        default=0, help_text="taxminiy xarajat, so'm"
                    ),
                ),
                (
                    "actual_cost",
                    models.BigIntegerField(
                        default=0, help_text="haqiqiy xarajat, so'm"
                    ),
                ),
                ("requires_proof", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
                (
                    "rework_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="necha marta qaytarilgan"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="ustun ichidagi tartib"
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="restoran o'zi qo'shgan maydonlar",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="core.branch",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watchers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="watched_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(max_length=32)),
                ("detail", models.CharField(blank=True, max_length=240)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "task activity",
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.JSONField(default=modules.tasks.models.empty_i18n)),
                ("icon", models.CharField(default="wrench", max_length=24)),
                ("color", models.CharField(default="#B7791F", max_length=9)),
                (
                    "sla_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="muddat: ochilgandan keyin necha soat"
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Past"),
                            ("normal", "O'rta"),
                            ("high", "Muhim"),
                            ("urgent", "Shoshilinch"),
                        ],
                        default="normal",
                        max_length=8,
                    ),
                ),
                (
                    "requires_proof",
                    models.BooleanField(
                        default=True,
                        help_text="tekshiruvga o'tishda foto-dalil majburiy",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="bajarildi deyish uchun nazoratchi tasdig'i",
                    ),
                ),
                (
                    "default_steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["Usta topish", "Materiallar olish", ...]',
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_task_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "task categories",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.taskcategory",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="tasks.taskcolumn",
            ),
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="tizim izohi (rad etish sababi va h.k.)",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.JSONField(default=modules.tasks.models.empty_i18n)),
                ("color", models.CharField(default="#0F6E63", max_length=9)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        help_text="bo'lim boshlig'i — nazoratchi sifatida standart tanlanadi",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="taskcategory",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="tasks.taskdepartment",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.taskdepartment",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tasks.tasklabel"
            ),
        ),
        migrations.CreateModel(
            name="TaskRecurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Past"),
                            ("normal", "O'rta"),
                            ("high", "Muhim"),
                            ("urgent", "Shoshilinch"),
                        ],
                        default="normal",
                        max_length=8,
                    ),
                ),
                ("steps", models.JSONField(blank=True, default=list)),
                (
                    "freq",
                    models.CharField(
                        choices=[
                            ("daily", "Har kuni"),
                            ("weekly", "Haftalik"),
                            ("monthly", "Oylik"),
                        ],
                        default="daily",
                        max_length=8,
                    ),
                ),
                (
                    "interval",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="har N kun/hafta/oy"
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[0..6] — 0 dushanba (weekly uchun)",
                    ),
                ),
                ("day_of_month", models.PositiveSmallIntegerField(default=1)),
                ("time_of_day", models.TimeField(default="09:00")),
                ("due_in_hours", models.PositiveIntegerField(default=8)),
                ("is_active", models.BooleanField(default=True)),
                ("last_created_on", models.DateField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.branch",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.taskcategory",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.taskdepartment",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_supervised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="tasks.taskrecurrence",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalTask",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "number",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        help_text="#1238 — restoran ichida ketma-ket",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Zal, 3-stol / Oshxona / Ombor",
                        max_length=120,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Past"),
                            ("normal", "O'rta"),
                            ("high", "Muhim"),
                            ("urgent", "Shoshilinch"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=8,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Qo'lda"),
                            ("issue", "Muammo (xodim aniqladi)"),
                            ("recurring", "Takroriy"),
                            ("checklist", "Checklist"),
                            ("system", "Tizim"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="tekshiruvga topshirilgan vaqt", null=True
                    ),
                ),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.BigIntegerField(
                        default=0, help_text="taxminiy xarajat, so'm"
                    ),
                ),
                (
                    "actual_cost",
                    models.BigIntegerField(
                        default=0, help_text="haqiqiy xarajat, so'm"
                    ),
                ),
                ("requires_proof", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
                (
                    "rework_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="necha marta qaytarilgan"
                    ),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="restoran o'zi qo'shgan maydonlar",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tasks.task",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tasks.taskcategory",
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tasks.taskcolumn",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tasks.taskdepartment",
                    ),
                ),
                (
                    "recurrence",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tasks.taskrecurrence",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical task",
                "verbose_name_plural": "historical tasks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TaskStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("is_done", models.BooleanField(default=False)),
                ("requires_photo", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="tasks/%Y/%m/")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("photo", "Muammo rasmi"),
                            ("proof", "Bajarilgan ish dalili"),
                            ("doc", "Hujjat"),
                        ],
                        default="photo",
                        max_length=6,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=160)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="tasks.taskstep",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["column", "sort_order"], name="tasks_task_column__2f54ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["branch", "priority"], name="tasks_task_branch__2edd67_idx"
            ),
        ),
    ]
